name: Publish Package

on:
  push:
    branches:
      - master
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@vinayg-cp'
      - run: npm install
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#           NODE_AUTH_TOKEN: ${{secrets.GPR_PAT}}
        run: npm publish
          
          
          
